// Generated by CoffeeScript 1.7.1
(function() {
  var lastScenarios;

  window.deleteNotifications = function() {
    $("#notifications-menu").html("<li class='dropdown-header'>No new notifications!</li>");
    $("#notifications-toggle").html("<span class='glyphicon glyphicon-bullhorn' />");
    $.ajax({
      url: "/notifications/delete"
    });
  };


  /* 
     * handlers for events on challenge form
   */

  window.dyo = function() {
    if ($("#dyo").is(":checked")) {
      $("#scenario").attr("disabled", "disabled");
    } else {
      $("#scenario").removeAttr("disabled");
    }
  };

  lastScenarios = [];

  window.scenario = function() {
    var text;
    text = $("#scenarioText").val();
    if (text) {
      return $.ajax("/ajax/scenario/" + encodeURI(text)).done(function(results, status) {
        var html, i, result, _i, _len;
        console.log(results);
        html = "";
        lastScenarios = results;
        i = 0;
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          html += "<a href='javascript:window.selectScenario(" + i + ")'> <strong>" + result.number + "</strong> - " + result.title + "</a><br />";
          i = i + 1;
        }
        return $("#scenario-area .suggestions").html(html);
      });
    }
  };

  window.opponent = function() {
    var text;
    text = $("#opponent").val();
    if (text) {
      return $.ajax("/ajax/user/" + encodeURI(text)).done(function(results, status) {
        var html, result, _i, _len;
        html = "";
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          html += "<a href=\"javascript:window.selectUser('" + result.name + "');\">" + result.name + "</a>&nbsp;";
        }
        return $("#opponent-area .suggestions").html(html);
      });
    }
  };


  /*
     *
   */

  window.selectScenario = function(i) {
    var sc, _ref, _ref1;
    sc = lastScenarios[i];
    $("#scenarioText").val(sc.number + " - " + sc.title);
    $("input[name=scenario]").val(sc._id);
    $("option[value=A]").html((((_ref = sc.attacker) != null ? _ref.nation : void 0) || "") + " (Attacker)");
    $("option[value=B]").html((((_ref1 = sc.defender) != null ? _ref1.nation : void 0) || "") + " (Defender)");
  };

  window.selectUser = function(user) {
    $("#opponent").val(user);
  };


  /*
     *  tabbing
   */

  $("a[data-toggle='tab']").on("shown.bs.tab", function(event) {
    event.preventDefault;
    return $(event.target).tab("show");
  });

}).call(this);
