// Generated by CoffeeScript 1.7.1
(function() {
  window.deleteNotifications = function() {
    $("#notifications-menu").html("<li class='dropdown-header'>No new notifications!</li>");
    $("#notifications-toggle").html("<span class='glyphicon glyphicon-bullhorn' />");
    $.ajax({
      url: "/notifications/delete"
    });
  };


  /* 
     * handlers for events on challenge form
   */

  window.dyo = function() {
    if ($("#dyo").is(":checked")) {
      $("#scenario").attr("disabled", "disabled");
    } else {
      $("#scenario").removeAttr("disabled");
    }
  };

  window.scenario = function() {
    var text;
    text = $("#scenario").val();
    if (text) {
      return $.ajax("/ajax/scenario/" + encodeURI(text)).done(function(results, status) {
        var html, result, _i, _len;
        console.log(results);
        html = "";
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          html += "<a href='javascript:window.selectScenario(\"" + result.number + "\", \"" + result.title + "\")'><strong>" + result.number + "</strong> - " + result.title + "</a>&nbsp;";
        }
        return $("#scenario-area .suggestions").html(html);
      });
    }
  };

  window.opponent = function() {
    var text;
    text = $("#opponent").val();
    if (text) {
      return $.ajax("/ajax/user/" + encodeURI(text)).done(function(results, status) {
        var html, result, _i, _len;
        html = "";
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          html += "<a href=\"javascript:window.selectUser('" + result.name + "');\">" + result.name + "</a>&nbsp;";
        }
        return $("#opponent-area .suggestions").html(html);
      });
    }
  };


  /*
     *
   */

  window.selectScenario = function(number, title) {
    $("#scenario").val(number + " - " + title);
  };

  window.selectUser = function(user) {
    $("#opponent").val(user);
  };


  /*
     *  tabbing
   */

  $("a[data-toggle='tab']").on("shown.bs.tab", function(event) {
    event.preventDefault;
    return $(event.target).tab("show");
  });

}).call(this);
