// Generated by CoffeeScript 1.7.1
(function() {
  window.deleteNotifications = function() {
    $("#notifications-menu").html("<li class='dropdown-header'>No new notifications!</li>");
    $("#notifications-toggle").html("Notifications");
    $.ajax({
      url: "/notifications/delete"
    });
  };


  /* 
     * handlers for events on challenge form
   */

  window.dyo = function() {
    if ($("#dyo").is(":checked")) {
      $("#scenario").attr("disabled", "disabled");
    } else {
      $("#scenario").removeAttr("disabled");
    }
  };


  /*
  window.scenario = () ->
    text = $("#scenario").val()
    if text
      $.ajax "/ajax/scenario/"+encodeURI(text)
        .done (result, status) ->
          console.log result # TODO reasonable handling here
          alert result
   */

  $(function() {
    return $('.form-group #scenario').typeahead(null, {
      name: 'scenario-matches',
      displayKey: 'value',
      remote: "/ajax/scenario/%QUERY"
    });
  });

}).call(this);
